    [package]
    name = "ores-otel-web-server"
    version = "0.1.0"
    edition = "2021"
    license = "MIT"
    description = "MASH web server for ores-otel"
    repository = "https://github.com/ores-otel/ores-otel-web-server.rs"

    [features]
    default = ["tcp-transport", "nats-transport"]
    tcp-transport = []
    nats-transport = []

    [dependencies]
    serde = { version = "1", features = ["derive"] }
    serde_json = "1"
    thiserror = "2"
    flags2env = { git = "https://github.com/ORESoftware/flags-2-env.git", rev = "377bff1a4e7424eb98377997a232ddc0fc700f59" }

[lints.rust]
unsafe_code = "forbid"


