// Generated by flags-2-env from .cli-flags.toml. Do not edit.
#![allow(dead_code)]

pub const API_HTTP_BASE: &str = "ORES_OTEL_API_HTTP_BASE";
pub const BIND: &str = "ORES_OTEL_WEB_BIND";
pub const BIND_DEFAULT: &str = "127.0.0.1:8081";
pub const DATABASE_URL: &str = "ORES_OTEL_DATABASE_URL";

/// Compile-time env key names from `.cli-flags.toml`.
pub struct CliEnv {
    /// API HTTP base URL.
    pub api_http_base: &'static str,
    /// HTTP bind address.
    pub bind: &'static str,
    /// Optional database URL for direct reads.
    pub database_url: &'static str,
}

impl CliEnv {
    pub const KEYS: Self = Self {
        api_http_base: API_HTTP_BASE,
        bind: BIND,
        database_url: DATABASE_URL,
    };
}

// Generated by flags-2-env from .cli-flags.toml. Do not edit.

/// Runtime values read from a lookup of env keys.
#[derive(Clone, Debug, PartialEq)]
pub struct CliEnvValues {
    pub api_http_base: Option<String>,
    pub bind: String,
    pub database_url: Option<String>,
}

/// Pure: resolve values from an explicit lookup.
pub fn load_from(lookup: impl Fn(&str) -> Option<String>) -> CliEnvValues {
    CliEnvValues {
        api_http_base: lookup("ORES_OTEL_API_HTTP_BASE").filter(|value| !value.is_empty()),
        bind: lookup("ORES_OTEL_WEB_BIND").filter(|value| !value.is_empty()).unwrap_or_else(|| "127.0.0.1:8081".to_string()),
        database_url: lookup("ORES_OTEL_DATABASE_URL").filter(|value| !value.is_empty()),
    }
}

/// Effectful: read the process environment.
pub fn load_from_os() -> CliEnvValues {
    load_from(|key| std::env::var(key).ok())
}

fn parse_bool(raw: Option<String>, default: bool) -> bool {
    match raw.as_deref().map(str::trim) {
        Some("1" | "true" | "TRUE" | "yes" | "YES") => true,
        Some("0" | "false" | "FALSE" | "no" | "NO") => false,
        Some(_) | None => default,
    }
}

fn parse_int(raw: Option<String>, default: i64) -> i64 {
    raw.and_then(|value| value.parse().ok()).unwrap_or(default)
}

fn parse_float(raw: Option<String>, default: f64) -> f64 {
    raw.and_then(|value| value.parse().ok()).unwrap_or(default)
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MissingEnv {
    pub name: &'static str,
    pub expected_type: &'static str,
    pub examples: &'static [&'static str],
}

impl std::fmt::Display for MissingEnv {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "missing required environment variable {}\n  expected type: {}\n  examples: {}", self.name, self.expected_type, self.examples.join(", "))
    }
}

impl std::error::Error for MissingEnv {}

fn nonempty(raw: Option<&str>) -> Option<String> {
    raw.map(str::trim).filter(|value| !value.is_empty()).map(str::to_string)
}

fn require_env(
    name: &'static str,
    expected_type: &'static str,
    examples: &'static [&'static str],
    value: Option<String>,
) -> Result<String, MissingEnv> {
    match nonempty(value.as_deref()) {
        Some(value) => Ok(value),
        None => Err(MissingEnv {
            name,
            expected_type,
            examples,
        }),
    }
}

fn pick(
    keys: &[&str],
    order: &[&str],
    shell: &std::collections::BTreeMap<String, String>,
    dotenv: &std::collections::BTreeMap<String, String>,
    flags: &std::collections::BTreeMap<String, String>,
    default: Option<&str>,
) -> Option<String> {
    for source in order {
        let map = match *source {
            "flags" => flags,
            "env_file" => dotenv,
            _ => shell,
        };
        for key in keys {
            if let Some(value) = nonempty(map.get(*key).map(String::as_str)) {
                return Some(value);
            }
        }
    }
    nonempty(default)
}

fn unquote(value: &str) -> String {
    let trimmed = value.trim();
    if trimmed.len() >= 2 {
        let bytes = trimmed.as_bytes();
        if (bytes[0] == b'"' && bytes[trimmed.len() - 1] == b'"')
            || (bytes[0] == b'\'' && bytes[trimmed.len() - 1] == b'\'')
        {
            return trimmed[1..trimmed.len() - 1].to_string();
        }
    }
    trimmed.to_string()
}

fn parse_dotenv(text: &str) -> std::collections::BTreeMap<String, String> {
    let mut out = std::collections::BTreeMap::new();
    for raw in text.lines() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let line = line.strip_prefix("export ").map(str::trim).unwrap_or(line);
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        let key = key.trim();
        if key.is_empty() {
            continue;
        }
        let first = key.chars().next().unwrap_or('\0');
        if !(first.is_ascii_alphabetic() || first == '_') {
            continue;
        }
        out.insert(key.to_string(), unquote(value));
    }
    out
}

fn dotenv_enabled() -> bool {
    match std::env::var("FLAGS2ENV_DOTENV") {
        Ok(value) if matches!(value.trim(), "0" | "false" | "FALSE" | "no" | "NO") => false,
        _ => true,
    }
}

fn load_dotenv_files(files: &[&str]) -> std::collections::BTreeMap<String, String> {
    if !dotenv_enabled() {
        return std::collections::BTreeMap::new();
    }
    files.iter().fold(std::collections::BTreeMap::new(), |mut acc, path| {
        if let Ok(text) = std::fs::read_to_string(path) {
            acc.extend(parse_dotenv(&text));
        }
        acc
    })
}

fn shell_env() -> std::collections::BTreeMap<String, String> {
    std::env::vars().collect()
}

/// Resolve env-key -> value. Empty values fall through to the next source.
pub fn load_env_map(
    shell: &std::collections::BTreeMap<String, String>,
    dotenv: &std::collections::BTreeMap<String, String>,
    flags: &std::collections::BTreeMap<String, String>,
) -> Result<std::collections::BTreeMap<String, String>, MissingEnv> {
    let mut out = std::collections::BTreeMap::new();
    let api_http_base = pick(&["ORES_OTEL_API_HTTP_BASE"], &["flags", "env_shell", "env_file"], shell, dotenv, flags, None);
    if let Some(value) = api_http_base {
        out.insert("ORES_OTEL_API_HTTP_BASE".to_string(), value);
    }
    let bind = pick(&["ORES_OTEL_WEB_BIND"], &["flags", "env_shell", "env_file"], shell, dotenv, flags, Some("127.0.0.1:8081"));
    if let Some(value) = bind {
        out.insert("ORES_OTEL_WEB_BIND".to_string(), value);
    }
    let database_url = pick(&["ORES_OTEL_DATABASE_URL"], &["flags", "env_shell", "env_file"], shell, dotenv, flags, None);
    if let Some(value) = database_url {
        out.insert("ORES_OTEL_DATABASE_URL".to_string(), value);
    }
    Ok(out)
}

/// Effectful overlay: `.env` files then the process environment, ranked per key.
pub fn load_env_map_from_os() -> Result<std::collections::BTreeMap<String, String>, MissingEnv> {
    load_env_map(&shell_env(), &load_dotenv_files(&[]), &std::collections::BTreeMap::new())
}
